apiVersion: apps/v1
kind: Deployment
metadata:
  name: wdj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wdj
  template:
    metadata:
      labels:
        app: wdj
    spec:
      containers:
      - image: okteto.dev/wdj:latest
        name: wdj
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.canva.com"
        - name: Vless_UUID
          value: "01291052-cf87-43ca-8eda-6bb71c117a94"
        - name: Vless_Path
          value: "/hfththy"
        - name: Vmess_UUID
          value: "01291052-cf87-43ca-8eda-6bb71c117a94"
        - name: Vmess_Path
          value: "/sefrgt"
        - name: Share_Path
          value: "/share233"
